//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class traduction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal traduction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TP1.Properties.traduction", typeof(traduction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string btn_add {
            get {
                return ResourceManager.GetString("btn_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string btn_erase {
            get {
                return ResourceManager.GetString("btn_erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        public static string column_amount {
            get {
                return ResourceManager.GetString("column_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string column_bool_illegal {
            get {
                return ResourceManager.GetString("column_bool_illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string column_bool_legal {
            get {
                return ResourceManager.GetString("column_bool_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidat.
        /// </summary>
        public static string column_candidate {
            get {
                return ResourceManager.GetString("column_candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Événement.
        /// </summary>
        public static string column_event_date {
            get {
                return ResourceManager.GetString("column_event_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Année Financière.
        /// </summary>
        public static string column_financial_yr {
            get {
                return ResourceManager.GetString("column_financial_yr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string column_FirstName {
            get {
                return ResourceManager.GetString("column_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illégale?.
        /// </summary>
        public static string column_illegal {
            get {
                return ResourceManager.GetString("column_illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string column_LastName {
            get {
                return ResourceManager.GetString("column_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipalité.
        /// </summary>
        public static string column_municipality {
            get {
                return ResourceManager.GetString("column_municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NB. Versements.
        /// </summary>
        public static string column_nb_payment {
            get {
                return ResourceManager.GetString("column_nb_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parti.
        /// </summary>
        public static string column_party {
            get {
                return ResourceManager.GetString("column_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string column_type {
            get {
                return ResourceManager.GetString("column_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Postal.
        /// </summary>
        public static string column_zip_code {
            get {
                return ResourceManager.GetString("column_zip_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier CSV non valide..
        /// </summary>
        public static string error_msg_csv {
            get {
                return ResourceManager.GetString("error_msg_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string information_caption {
            get {
                return ResourceManager.GetString("information_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;application va redémarrer pour appliquer les changements..
        /// </summary>
        public static string information_dialog_msg {
            get {
                return ResourceManager.GetString("information_dialog_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décompte.
        /// </summary>
        public static string lbl_Count {
            get {
                return ResourceManager.GetString("lbl_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue :.
        /// </summary>
        public static string lbl_language {
            get {
                return ResourceManager.GetString("lbl_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illégales Seulement.
        /// </summary>
        public static string lbl_only_illegal {
            get {
                return ResourceManager.GetString("lbl_only_illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Redémarrer après changements.
        /// </summary>
        public static string lbl_restart_after_changes {
            get {
                return ResourceManager.GetString("lbl_restart_after_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string menu_configuration {
            get {
                return ResourceManager.GetString("menu_configuration", resourceCulture);
            }
        }
    }
}
