//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciceMockEtTdd.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutresRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutresRessources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExerciceMockEtTdd.Properties.AutresRessources", typeof(AutresRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] drole {
            get {
                object obj = ResourceManager.GetObject("drole", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DROP TABLE IF EXISTS personne;
        ///
        ///CREATE TABLE personne
        ///(
        ///	id			INTEGER PRIMARY KEY,
        ///	nom			TEXT	NOT NULL,
        ///	prenom		TEXT	NOT NULL,
        ///	telephone	TEXT	NOT NULL
        ///);
        ///
        ///INSERT INTO personne VALUES (NULL, &apos;Carnaval&apos;, &apos;Bonhomme&apos;, &apos;418-123-4567&apos;);
        ///INSERT INTO personne VALUES (NULL, &apos;Gratton&apos;, &apos;Bob&apos;, &apos;450-659-8854&apos;);
        ///INSERT INTO personne VALUES (NULL, &apos;Troudeau&apos;, &apos;Justun&apos;, &apos;514-465-4785&apos;);
        ///INSERT INTO personne VALUES (NULL, &apos;Doué&apos;, &apos;Jél&apos;, &apos;819-567-0191&apos;);
        ///INSERT INTO personne VALUES (NULL, &apos;Ndong&apos;, &apos;Saliou&apos;, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string sqlite_script {
            get {
                return ResourceManager.GetString("sqlite_script", resourceCulture);
            }
        }
    }
}
