// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP4.DataService;

#nullable disable

namespace TP4.Migrations
{
    [DbContext(typeof(SqliteMeteoDbContext))]
    [Migration("20241212064522_CreationInitialeBdSqlite")]
    partial class CreationInitialeBdSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TP4.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 46.56984172477484,
                            Longitude = -72.738112856514419,
                            Nom = "Shawinigan"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 36.753799999999998,
                            Longitude = 3.0588000000000002,
                            Nom = "Algiers"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 35.697099999999999,
                            Longitude = -0.63080000000000003,
                            Nom = "Oran"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 36.365000000000002,
                            Longitude = 6.6147,
                            Nom = "Constantine"
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 36.899999999999999,
                            Longitude = 7.766,
                            Nom = "Annaba"
                        },
                        new
                        {
                            Id = 6,
                            Latitude = 36.470100000000002,
                            Longitude = 2.8277000000000001,
                            Nom = "Blida"
                        },
                        new
                        {
                            Id = 7,
                            Latitude = 35.555,
                            Longitude = 6.1744000000000003,
                            Nom = "Batna"
                        },
                        new
                        {
                            Id = 8,
                            Latitude = 34.878300000000003,
                            Longitude = -1.3149999999999999,
                            Nom = "Tlemcen"
                        },
                        new
                        {
                            Id = 9,
                            Latitude = 36.192,
                            Longitude = 5.4138000000000002,
                            Nom = "Sétif"
                        },
                        new
                        {
                            Id = 10,
                            Latitude = 36.750900000000001,
                            Longitude = 5.0566000000000004,
                            Nom = "Béjaïa"
                        },
                        new
                        {
                            Id = 11,
                            Latitude = 32.4908,
                            Longitude = 3.6735000000000002,
                            Nom = "Ghardaïa"
                        },
                        new
                        {
                            Id = 12,
                            Latitude = 36.716999999999999,
                            Longitude = 4.0458999999999996,
                            Nom = "Tizi Ouzou"
                        },
                        new
                        {
                            Id = 13,
                            Latitude = 36.866199999999999,
                            Longitude = 6.9066999999999998,
                            Nom = "Skikda"
                        },
                        new
                        {
                            Id = 14,
                            Latitude = 34.8504,
                            Longitude = 5.7279999999999998,
                            Nom = "Biskra"
                        },
                        new
                        {
                            Id = 15,
                            Latitude = 27.876100000000001,
                            Longitude = -0.28320000000000001,
                            Nom = "Adrar"
                        },
                        new
                        {
                            Id = 16,
                            Latitude = 33.803600000000003,
                            Longitude = 2.8828999999999998,
                            Nom = "Laghouat"
                        },
                        new
                        {
                            Id = 17,
                            Latitude = 22.785,
                            Longitude = 5.5228000000000002,
                            Nom = "Tamanrasset"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
